# Generated by Django 4.0.4 on 2022-05-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('damage', models.IntegerField()),
                ('nbr_ammo', models.IntegerField()),
                ('image', models.URLField(null=True)),
            ],
        ),
    ]
