# Generated by Django 4.0.4 on 2022-05-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_create', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.IntegerField()),
                ('role', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('profile', models.URLField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WT',
        ),
    ]
