# Generated by Django 4.0.4 on 2022-05-10 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player_create', '0002_player_delete_wt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('logo', models.URLField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='player_create.team_models'),
        ),
    ]
