# Generated by Django 4.0.4 on 2022-05-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_create', '0003_team_models_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('Star Player', 'Awper'), ('Entry', 'Lurker'), ('Second Entry', 'Leader IG'), ('Fix BP', 'Pivot')], max_length=20),
        ),
    ]
