# Generated by Django 4.0.4 on 2022-05-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_create', '0004_alter_player_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('Star_Player', 'Star Player'), ('Awper', 'Awper'), ('Lurker', 'Lurker'), ('Entry', 'Entry'), ('2Entry', 'Second Entry'), ('leader', 'Leader IG'), ('fix_bp', 'Fix BP'), ('pivot', 'Pivot')], max_length=20),
        ),
    ]
