# Generated by Django 4.0.4 on 2022-05-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_create', '0005_alter_player_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('Star Player', 'Star Player'), ('Awper', 'Awper'), ('Lurker', 'Lurker'), ('Entry', 'Entry'), ('Second Entry', 'Second Entry'), ('Leader IG', 'Leader IG'), ('Fix BP', 'Fix BP'), ('Pivot', 'Pivot')], max_length=20),
        ),
    ]
