# Generated by Django 4.0.4 on 2022-05-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_create', '0006_alter_player_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.CharField(choices=[('-18 ans', '-18 ans'), ('entre 18 et 26', 'entre 18 et 26'), ('+26 ans', '+26 ans')], max_length=20),
        ),
        migrations.AlterField(
            model_name='team_models',
            name='location',
            field=models.CharField(choices=[('Europe', 'EU'), ('Amérique', 'USA'), ('Russie', 'RU'), ('Asie', 'AS')], max_length=20),
        ),
    ]
