# Generated by Django 4.0.4 on 2022-05-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_create', '0007_alter_player_age_alter_team_models_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_without_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.IntegerField()),
                ('role', models.CharField(choices=[('Star Player', 'Star Player'), ('Awper', 'Awper'), ('Lurker', 'Lurker'), ('Entry', 'Entry'), ('Second Entry', 'Second Entry'), ('Leader IG', 'Leader IG'), ('Fix BP', 'Fix BP'), ('Pivot', 'Pivot')], max_length=20)),
                ('age', models.CharField(choices=[('-18 ans', '-18 ans'), ('entre 18 et 26', 'entre 18 et 26'), ('+26 ans', '+26 ans')], max_length=20)),
                ('profile', models.URLField(null=True)),
            ],
        ),
    ]
