# Generated by Django 4.0.4 on 2022-05-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_create', '0009_alter_team_models_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nom',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='player',
            name='prix',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='player_without_team',
            name='nom',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='player_without_team',
            name='prix',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='team_models',
            name='nom',
            field=models.CharField(max_length=20),
        ),
    ]
