# Generated by Django 4.0.4 on 2022-05-11 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_create', '0011_alter_player_prix_alter_player_without_team_prix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='prix',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
