# Generated by Django 4.0.4 on 2022-05-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_create', '0012_alter_player_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='prix',
            field=models.IntegerField(),
        ),
    ]
