# Generated by Django 4.0.4 on 2022-05-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_create', '0015_delete_player_without_team_alter_player_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_models',
            name='nom',
            field=models.CharField(max_length=15),
        ),
    ]
